# 📊 Exploration des Données Crypto - Phase 1

Ce notebook explore les données historiques collectées depuis Binance.

## Objectifs
1. Charger et visualiser les données collectées
2. Analyser les statistiques descriptives
3. Détecter les valeurs manquantes et anomalies
4. Visualiser les tendances de prix et volumes
5. Analyser les corrélations entre cryptos
6. Calculer les rendements et volatilité

In [1]:
# Imports
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.graph_objects as go
import plotly.express as px
from plotly.subplots import make_subplots
from pathlib import Path
import warnings
from datetime import datetime, timedelta

warnings.filterwarnings('ignore')

# Configuration des graphiques
plt.style.use('seaborn-v0_8-darkgrid')
sns.set_palette('husl')
%matplotlib inline

# Configuration pandas
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', 100)
pd.set_option('display.float_format', '{:.2f}'.format)

print("✅ Imports réussis!")
print(f"📅 Date d'exécution: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")

✅ Imports réussis!
📅 Date d'exécution: 2025-11-25 16:53:17

## 1. 📁 Chargement des Données

In [2]:
# Chemin des données
data_path = Path('../data/raw/historical')

# Lister tous les fichiers CSV
csv_files = list(data_path.glob('*.csv'))

print(f"📂 Fichiers CSV trouvés: {len(csv_files)}")
print("\n📋 Liste des fichiers CSV:")
for f in csv_files:
    size_kb = f.stat().st_size / 1024
    print(f"  • {f.name} ({size_kb:.2f} KB)")

📂 Fichiers CSV trouvés: 15

📋 Liste des fichiers CSV:
  • UNI_USDT_1h_20251123.csv (43.86 KB)
  • AVAX_USDT_1h_20251123.csv (44.36 KB)
  • ETH_USDT_4h_20251121.csv (37.72 KB)
  • BTC_USDT_1h_20251121.csv (54.52 KB)
  • DOT_USDT_1h_20251123.csv (43.93 KB)
  • BTC_USDT_1h_20251123.csv (54.33 KB)
  • LINK_USDT_1h_20251123.csv (44.51 KB)
  • BTC_USDT_4h_20251121.csv (41.49 KB)
  • ADA_USDT_1h_20251123.csv (46.93 KB)
  • USDT_TRY_1h_20251121.csv (43.86 KB)
  • USDT_TRY_1h_20251123.csv (10.28 KB)
  • ETH_USDT_1h_20251123.csv (50.00 KB)
  • BNB_USDT_1h_20251123.csv (47.24 KB)
  • USDT_ARS_1h_20251121.csv (45.90 KB)
  • SOL_USDT_1h_20251123.csv (47.24 KB)

In [3]:
# Fonction pour charger tous les fichiers
def load_all_crypto_data(data_path):
    crypto_data = {}
    for csv_file in data_path.glob('*.csv'):
        try:
            df = pd.read_csv(csv_file)
            df['timestamp'] = pd.to_datetime(df['timestamp'])
            symbol = df['symbol'].iloc[0] if 'symbol' in df.columns else csv_file.stem
            crypto_data[symbol] = df
            print(f"✓ {symbol}: {len(df)} lignes chargées")
        except Exception as e:
            print(f"✗ Erreur avec {csv_file.name}: {e}")
    return crypto_data

crypto_data = load_all_crypto_data(data_path)
print(f"\n✅ {len(crypto_data)} cryptos chargées avec succès!")

✓ UNI/USDT: 720 lignes chargées
✓ AVAX/USDT: 720 lignes chargées
✓ ETH/USDT: 540 lignes chargées
✓ BTC/USDT: 720 lignes chargées
✓ DOT/USDT: 720 lignes chargées
✓ BTC/USDT: 720 lignes chargées
✓ LINK/USDT: 720 lignes chargées
✓ BTC/USDT: 540 lignes chargées
✓ ADA/USDT: 720 lignes chargées
✓ USDT/TRY: 720 lignes chargées
✓ USDT/TRY: 168 lignes chargées
✓ ETH/USDT: 720 lignes chargées
✓ BNB/USDT: 720 lignes chargées
✓ USDT/ARS: 720 lignes chargées
✓ SOL/USDT: 720 lignes chargées

✅ 11 cryptos chargées avec succès!

## 2. 🔍 Aperçu des Données

In [5]:
# Afficher un aperçu
for symbol, df in crypto_data.items():
    print(f"\n{'='*70}")
    print(f"📊 {symbol}")
    print(f"{'='*70}")
    print(f"Période: {df['timestamp'].min()} à {df['timestamp'].max()}")
    print(f"Bougies: {len(df)}")
    display(df.head())
    display(df.describe())

======================================================================
📊 UNI/USDT
======================================================================
Période: 2025-10-24 06:00:00 à 2025-11-23 05:00:00
Bougies: 720

            timestamp  open  high  low  close   volume    symbol
0 2025-10-24 06:00:00  6.40  6.42 6.39   6.40 81030.64  UNI/USDT
1 2025-10-24 07:00:00  6.40  6.40 6.34   6.36 72516.75  UNI/USDT
2 2025-10-24 08:00:00  6.36  6.42 6.33   6.38 86691.32  UNI/USDT
3 2025-10-24 09:00:00  6.38  6.39 6.37   6.38 42895.87  UNI/USDT
4 2025-10-24 10:00:00  6.38  6.38 6.35   6.35 35200.22  UNI/USDT

                           timestamp   open   high    low  close     volume
count                            720 720.00 720.00 720.00 720.00     720.00
mean   2025-11-08 05:29:59.999999744   6.55   6.62   6.49   6.55  460362.78
min              2025-10-24 06:00:00   4.92   4.97   4.74   4.92   18913.11
25%              2025-10-31 17:45:00   5.86   5.89   5.83   5.86  129657.91
50%              2025-11-08 05:30:00   6.38   6.44   6.33   6.38  250230.85
75%              2025-11-15 17:15:00   7.27   7.34   7.20   7.27  485288.97
max              2025-11-23 05:00:00   9.61  10.30   9.34   9.62 7951038.14
std                              NaN   0.94   0.98   0.90   0.94  793440.96

======================================================================
📊 AVAX/USDT
======================================================================
Période: 2025-10-24 06:00:00 à 2025-11-23 05:00:00
Bougies: 720

            timestamp  open  high   low  close   volume     symbol
0 2025-10-24 06:00:00 19.61 19.63 19.55  19.61 67549.53  AVAX/USDT
1 2025-10-24 07:00:00 19.61 19.63 19.40  19.49 66106.62  AVAX/USDT
2 2025-10-24 08:00:00 19.50 19.67 19.41  19.59 86671.72  AVAX/USDT
3 2025-10-24 09:00:00 19.60 19.62 19.54  19.56 46832.02  AVAX/USDT
4 2025-10-24 10:00:00 19.57 19.58 19.49  19.50 35172.25  AVAX/USDT

                           timestamp   open   high    low  close     volume
count                            720 720.00 720.00 720.00 720.00     720.00
mean   2025-11-08 05:29:59.999999744  17.06  17.17  16.93  17.05  141362.75
min              2025-10-24 06:00:00  12.93  13.11  12.57  12.92   17559.91
25%              2025-10-31 17:45:00  15.59  15.67  15.42  15.58   66105.36
50%              2025-11-08 05:30:00  17.19  17.33  17.04  17.18  105048.54
75%              2025-11-15 17:15:00  18.55  18.65  18.46  18.54  172054.64
max              2025-11-23 05:00:00  20.97  21.10  20.94  20.98 1932442.80
std                              NaN   2.07   2.08   2.08   2.08  137302.32

======================================================================
📊 ETH/USDT
======================================================================
Période: 2025-10-24 08:00:00 à 2025-11-23 07:00:00
Bougies: 720

            timestamp    open    high     low   close   volume    symbol
0 2025-10-24 08:00:00 3949.22 3965.00 3930.54 3952.86 23504.12  ETH/USDT
1 2025-10-24 09:00:00 3952.86 3969.81 3949.94 3958.57 15304.52  ETH/USDT
2 2025-10-24 10:00:00 3958.58 3964.90 3947.72 3956.60  6249.49  ETH/USDT
3 2025-10-24 11:00:00 3956.60 3963.92 3925.83 3946.57 13446.01  ETH/USDT
4 2025-10-24 12:00:00 3946.58 4026.39 3941.52 3963.97 57286.43  ETH/USDT

                 timestamp    open    high     low   close    volume
count                  720  720.00  720.00  720.00  720.00    720.00
mean   2025-11-08 07:30:00 3484.38 3502.51 3462.11 3482.78  25274.45
min    2025-10-24 08:00:00 2681.41 2717.14 2623.57 2681.42   1788.27
25%    2025-10-31 19:45:00 3176.03 3193.60 3154.73 3175.38  10630.15
50%    2025-11-08 07:30:00 3445.24 3463.03 3429.09 3444.31  18160.09
75%    2025-11-15 19:15:00 3867.21 3877.13 3854.65 3866.46  31742.20
max    2025-11-23 07:00:00 4235.21 4253.72 4222.80 4235.21 185535.45
std                    NaN  400.28  398.45  403.66  400.73  23188.36

======================================================================
📊 BTC/USDT
======================================================================
Période: 2025-08-23 04:00:00 à 2025-11-21 00:00:00
Bougies: 540

,timestamp,open,high,low,close,volume,symbol
0,2025-08-23 04:00:00,115568.77,116034.53,115551.20,115799.47,2258.18,BTC/USDT
1,2025-08-23 08:00:00,115799.46,115861.80,115223.43,115310.13,1313.89,BTC/USDT
2,2025-08-23 12:00:00,115310.13,115486.97,114560.00,114812.87,3027.56,BTC/USDT
3,2025-08-23 16:00:00,114812.88,115190.74,114684.11,115133.91,1105.55,BTC/USDT
4,2025-08-23 20:00:00,115133.92,115454.12,115001.88,115438.05,976.59,BTC/USDT

                 timestamp      open      high       low     close   volume
count                  540    540.00    540.00    540.00    540.00   540.00
mean   2025-10-07 02:00:00 110513.97 111097.30 109802.88 110461.18  3328.31
min    2025-08-23 04:00:00  86637.22  87498.94  86100.00  86637.23   452.79
25%    2025-09-14 15:00:00 108315.65 108791.67 107455.37 108284.84  1621.97
50%    2025-10-07 02:00:00 111261.24 111768.42 110612.68 111260.23  2547.14
75%    2025-10-29 13:00:00 114814.94 115439.98 114224.82 114750.88  4008.17
max    2025-11-21 00:00:00 125410.80 126199.63 124800.00 125410.81 41734.73
std                    NaN   7050.89   7037.44   7204.09   7119.35  2922.45

======================================================================
📊 DOT/USDT
======================================================================
Période: 2025-10-24 06:00:00 à 2025-11-23 05:00:00
Bougies: 720

            timestamp  open  high  low  close    volume    symbol
0 2025-10-24 06:00:00  3.06  3.06 3.04   3.06 328963.43  DOT/USDT
1 2025-10-24 07:00:00  3.06  3.07 3.04   3.05 210093.27  DOT/USDT
2 2025-10-24 08:00:00  3.05  3.08 3.04   3.07 198534.66  DOT/USDT
3 2025-10-24 09:00:00  3.07  3.07 3.06   3.06 119171.12  DOT/USDT
4 2025-10-24 10:00:00  3.06  3.06 3.04   3.04 162203.86  DOT/USDT

                           timestamp   open   high    low  close     volume
count                            720 720.00 720.00 720.00 720.00     720.00
mean   2025-11-08 05:29:59.999999744   2.89   2.91   2.86   2.89  393202.39
min              2025-10-24 06:00:00   2.27   2.29   2.25   2.27   32836.60
25%              2025-10-31 17:45:00   2.72   2.74   2.70   2.72  160987.00
50%              2025-11-08 05:30:00   2.90   2.91   2.88   2.90  266881.29
75%              2025-11-15 17:15:00   3.09   3.11   3.08   3.09  460874.43
max              2025-11-23 05:00:00   3.44   3.53   3.38   3.44 4235137.92
std                              NaN   0.25   0.26   0.26   0.25  441062.59

======================================================================
📊 LINK/USDT
======================================================================
Période: 2025-10-24 06:00:00 à 2025-11-23 05:00:00
Bougies: 720

            timestamp  open  high   low  close    volume     symbol
0 2025-10-24 06:00:00 17.67 17.72 17.60  17.70  59134.06  LINK/USDT
1 2025-10-24 07:00:00 17.71 17.73 17.55  17.65 139217.10  LINK/USDT
2 2025-10-24 08:00:00 17.65 17.82 17.57  17.73 295354.81  LINK/USDT
3 2025-10-24 09:00:00 17.74 17.76 17.66  17.67 167799.78  LINK/USDT
4 2025-10-24 10:00:00 17.67 17.68 17.60  17.64  47918.54  LINK/USDT

                           timestamp   open   high    low  close     volume
count                            720 720.00 720.00 720.00 720.00     720.00
mean   2025-11-08 05:29:59.999999744  15.59  15.70  15.46  15.58  206168.21
min              2025-10-24 06:00:00  11.79  11.91  11.61  11.79   23149.17
25%              2025-10-31 17:45:00  14.15  14.21  14.03  14.14   98843.52
50%              2025-11-08 05:30:00  15.41  15.51  15.29  15.41  151561.12
75%              2025-11-15 17:15:00  17.26  17.34  17.16  17.26  236791.00
max              2025-11-23 05:00:00  19.01  19.06  18.89  19.01 2486034.14
std                              NaN   1.86   1.86   1.87   1.87  197536.57

======================================================================
📊 ADA/USDT
======================================================================
Période: 2025-10-24 08:00:00 à 2025-11-23 07:00:00
Bougies: 720

            timestamp  open  high  low  close      volume    symbol
0 2025-10-24 08:00:00  0.65  0.65 0.65   0.65  3123580.90  ADA/USDT
1 2025-10-24 09:00:00  0.65  0.65 0.65   0.65  1676702.50  ADA/USDT
2 2025-10-24 10:00:00  0.65  0.65 0.65   0.65  1894073.70  ADA/USDT
3 2025-10-24 11:00:00  0.65  0.65 0.64   0.65  5134912.50  ADA/USDT
4 2025-10-24 12:00:00  0.65  0.66 0.65   0.65 16042774.00  ADA/USDT

                 timestamp   open   high    low  close      volume
count                  720 720.00 720.00 720.00 720.00      720.00
mean   2025-11-08 07:30:00   0.56   0.56   0.55   0.56  6217243.63
min    2025-10-24 08:00:00   0.39   0.40   0.39   0.39   760748.40
25%    2025-10-31 19:45:00   0.50   0.51   0.50   0.50  2788668.42
50%    2025-11-08 07:30:00   0.56   0.56   0.56   0.56  4319480.25
75%    2025-11-15 19:15:00   0.61   0.61   0.61   0.61  7210122.17
max    2025-11-23 07:00:00   0.69   0.69   0.69   0.69 77131549.50
std                    NaN   0.08   0.08   0.08   0.08  6662870.88

======================================================================
📊 USDT/TRY
======================================================================
Période: 2025-11-16 06:00:00 à 2025-11-23 05:00:00
Bougies: 168

            timestamp  open  high   low  close     volume    symbol
0 2025-11-16 06:00:00 42.48 42.49 42.43  42.44 1271822.00  USDT/TRY
1 2025-11-16 07:00:00 42.44 42.44 42.42  42.42 1362961.00  USDT/TRY
2 2025-11-16 08:00:00 42.43 42.43 42.42  42.43 1287382.00  USDT/TRY
3 2025-11-16 09:00:00 42.42 42.43 42.42  42.43 1064975.00  USDT/TRY
4 2025-11-16 10:00:00 42.43 42.43 42.42  42.43 1133207.00  USDT/TRY

                           timestamp   open   high    low  close     volume
count                            168 168.00 168.00 168.00 168.00     168.00
mean   2025-11-19 17:30:00.000000256  42.43  42.44  42.42  42.43 2314975.75
min              2025-11-16 06:00:00  42.29  42.30  42.29  42.29  243355.00
25%              2025-11-17 23:45:00  42.35  42.36  42.34  42.35 1051924.25
50%              2025-11-19 17:30:00  42.39  42.39  42.37  42.39 1999444.50
75%              2025-11-21 11:15:00  42.51  42.54  42.49  42.53 2889986.25
max              2025-11-23 05:00:00  42.60  42.60  42.59  42.60 8721249.00
std                              NaN   0.10   0.10   0.10   0.10 1768987.77

======================================================================
📊 BNB/USDT
======================================================================
Période: 2025-10-24 08:00:00 à 2025-11-23 07:00:00
Bougies: 720

            timestamp    open    high     low   close   volume    symbol
0 2025-10-24 08:00:00 1125.24 1130.32 1121.04 1128.06 13845.68  BNB/USDT
1 2025-10-24 09:00:00 1128.06 1135.85 1126.65 1130.20 18750.88  BNB/USDT
2 2025-10-24 10:00:00 1130.19 1130.58 1123.94 1126.72 13569.95  BNB/USDT
3 2025-10-24 11:00:00 1126.71 1126.80 1120.27 1125.37 11219.80  BNB/USDT
4 2025-10-24 12:00:00 1125.37 1137.78 1123.03 1127.55 24362.05  BNB/USDT

                 timestamp    open    high     low   close    volume
count                  720  720.00  720.00  720.00  720.00    720.00
mean   2025-11-08 07:30:00  994.37  998.79  988.79  993.98  15185.39
min    2025-10-24 08:00:00  809.08  818.42  790.79  809.08   1420.40
25%    2025-10-31 19:45:00  930.70  934.76  924.69  930.58   7004.30
50%    2025-11-08 07:30:00  971.92  976.59  965.63  970.74  10990.97
75%    2025-11-15 19:15:00 1088.97 1091.57 1085.52 1088.91  18524.77
max    2025-11-23 07:00:00 1179.69 1182.60 1164.81 1179.70 142779.72
std                    NaN   91.45   91.04   92.09   91.50  14519.61

======================================================================
📊 USDT/ARS
======================================================================
Période: 2025-10-22 02:00:00 à 2025-11-21 01:00:00
Bougies: 720

            timestamp    open    high     low   close   volume    symbol
0 2025-10-22 02:00:00 1586.90 1592.10 1584.20 1590.00 64750.00  USDT/ARS
1 2025-10-22 03:00:00 1589.90 1591.90 1587.20 1589.10 43314.00  USDT/ARS
2 2025-10-22 04:00:00 1589.40 1593.90 1588.60 1589.40 16902.00  USDT/ARS
3 2025-10-22 05:00:00 1589.40 1590.10 1588.20 1589.70 11727.00  USDT/ARS
4 2025-10-22 06:00:00 1589.70 1590.20 1589.40 1590.00  5982.00  USDT/ARS

                           timestamp    open    high     low   close    volume
count                            720  720.00  720.00  720.00  720.00    720.00
mean   2025-11-06 01:29:59.999999744 1501.43 1503.82 1498.61 1501.30  89877.18
min              2025-10-22 02:00:00 1404.00 1430.20 1390.00 1401.00   3307.00
25%              2025-10-29 13:45:00 1479.20 1480.85 1476.40 1479.10  29778.75
50%              2025-11-06 01:30:00 1492.05 1493.45 1490.50 1492.20  58675.00
75%              2025-11-13 13:15:00 1500.12 1501.53 1497.33 1500.03 111999.00
max              2025-11-21 01:00:00 1605.00 1607.30 1599.00 1604.00 838618.00
std                              NaN   36.27   36.15   36.07   36.12  99960.12

======================================================================
📊 SOL/USDT
======================================================================
Période: 2025-10-24 08:00:00 à 2025-11-23 07:00:00
Bougies: 720

            timestamp   open   high    low  close    volume    symbol
0 2025-10-24 08:00:00 192.15 193.45 191.70 192.97  81875.79  SOL/USDT
1 2025-10-24 09:00:00 192.96 193.39 191.88 192.11  78615.47  SOL/USDT
2 2025-10-24 10:00:00 192.11 192.16 191.44 191.78  84266.67  SOL/USDT
3 2025-10-24 11:00:00 191.78 192.20 190.58 192.13  76522.11  SOL/USDT
4 2025-10-24 12:00:00 192.13 197.00 192.13 193.66 471792.92  SOL/USDT

                 timestamp   open   high    low  close     volume
count                  720 720.00 720.00 720.00 720.00     720.00
mean   2025-11-08 07:30:00 163.49 164.46 162.29 163.41  178332.75
min    2025-10-24 08:00:00 124.32 126.37 121.66 124.32   16164.69
25%    2025-10-31 19:45:00 141.87 142.76 140.83 141.78   89432.11
50%    2025-11-08 07:30:00 159.45 160.91 158.54 159.44  134597.43
75%    2025-11-15 19:15:00 186.41 187.03 185.43 186.36  209359.75
max    2025-11-23 07:00:00 204.76 205.33 203.91 204.75 1906040.98
std                    NaN  23.30  23.24  23.37  23.32  156961.64

## 3. 📊 Visualisation des Prix

In [6]:
# Graphique des prix
fig = go.Figure()
for symbol, df in crypto_data.items():
    fig.add_trace(go.Scatter(
        x=df['timestamp'],
        y=df['close'],
        mode='lines',
        name=symbol
    ))

fig.update_layout(
    title='📈 Évolution des Prix',
    xaxis_title='Date',
    yaxis_title='Prix (USD)',
    height=600,
    template='plotly_dark'
)
fig.show()

## 🎯 Prochaines Étapes

1. Feature Engineering - Indicateurs techniques
2. Base de données - TimescaleDB
3. Modélisation ML
4. Prédictions